usage:
	echo "Tag all compila y ejecuta los 6 ejerecicios\n Tag ejer, uno en particular. Necesita el param file. Ejem: make ejer file=ejer1.c"
	ls
all:
	gcc ejer1.c -o bejer1 && ./bejer1 	
	gcc ejer2.c -o bejer2 && ./bejer2 	
	gcc ejer3.c -o bejer3 && ./bejer3 	
	gcc ejer4.c -o bejer4 && ./bejer4
	gcc ejer5.c -o bejer5 && ./bejer5
	gcc ejer6.c -o bejer6 && ./bejer6 	

ejer:
	gcc ${file} -o bejer && ./bejer  
clean:
	rm bejer*
